apiVersion: v1
data:
  accesskey: bWluaW8=
  secretkey: bWluaW8xMjM=
kind: Secret
metadata:
  labels:
    ksonnet.io/component: pipeline
  name: mlpipeline-minio-artifact
  namespace: kubeflow
type: Opaque