apiVersion: v1
kind: Service
metadata:
  labels:
    ksonnet.io/component: pipeline
  name: minio-service
  namespace: kubeflow
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: minio